---
- name: "Cleaning all audit logs"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/audit/audit.log
    - /var/log/lastlog
    - /var/log/wtmp

- name: "Cleaning persistent udev rules"
  ansible.builtin.file:
    path: /etc/udev/rules.d/70-persistent-net.rules
    state: absent

- name: "Find the /tmp directories"
  ansible.builtin.find:
    paths:
      - /tmp
      - /var/tmp
    file_type: any
  register: find_tmp_directories

- name: "Cleaning the /tmp directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ find_tmp_directories.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: "Find the SSH host keys"
  ansible.builtin.find:
    paths: /etc/ssh
    patterns: 'ssh_host_*'
  register: find_ssh_host_keys

- name: "Cleaning the SSH host keys"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ find_ssh_host_keys.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: "Cleaning the machine-id"
  block:
    - name: "Resize /etc/machine-id"
      community.general.filesize:
        path: /etc/machine-id
        size: 0B
    - name: "Remove /var/lib/dbus/machine-id"
      ansible.builtin.file:
        path: /var/lib/dbus/machine-id
        state: absent
    - name: "Create a sybmolic link"
      ansible.builtin.file:
        src: /etc/machine-id
        dest: /var/lib/dbus/machine-id
        state: link

- name: "Cleaning the shell history."
  shell: |
    unset HISTFILE
    history -cw
    echo > ~/.bash_history
    rm -fr /root/.bash_history